import { defineConfig, globalIgnores } from "eslint/config";
import nextVitals from "eslint-config-next/core-web-vitals";
import nextTs from "eslint-config-next/typescript";

const eslintConfig = defineConfig([
  ...nextVitals,
  ...nextTs,
  // Override default ignores of eslint-config-next.
  globalIgnores([
    // Default ignores of eslint-config-next:
    ".next/**",
    "out/**",
    "build/**",
    "next-env.d.ts",
    // Generated by `prisma contract emit` and migration snapshots.
    "src/prisma/contract.d.ts",
    "migrations/**",
    // One-off tooling scripts, not app code.
    "scratch/**",
    "apply-trigger.js",
    "drop-migrations.js",
    "drop-tables.js",
    // Agent skill folders synced by `prisma skills sync`.
    ".agents/**",
    ".claude/**",
    ".cursor/**",
    ".devin/**",
  ]),
]);

export default eslintConfig;
